/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HelpRouteImport } from './routes/help'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as DashboardSubjectLibraryRouteImport } from './routes/dashboard.subject-library'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardRepositoryRouteImport } from './routes/dashboard.repository'
import { Route as AdminSubjectLibraryRouteImport } from './routes/admin.subject-library'
import { Route as DashboardSummaryFilenameRouteImport } from './routes/dashboard.summary.$filename'
import { Route as DashboardQuizFilenameRouteImport } from './routes/dashboard.quiz.$filename'
import { Route as DashboardMcqFilenameRouteImport } from './routes/dashboard.mcq.$filename'
import { Route as DashboardChatFilenameRouteImport } from './routes/dashboard.chat.$filename'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const DashboardSubjectLibraryRoute = DashboardSubjectLibraryRouteImport.update({
  id: '/subject-library',
  path: '/subject-library',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRepositoryRoute = DashboardRepositoryRouteImport.update({
  id: '/repository',
  path: '/repository',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminSubjectLibraryRoute = AdminSubjectLibraryRouteImport.update({
  id: '/subject-library',
  path: '/subject-library',
  getParentRoute: () => AdminRoute,
} as any)
const DashboardSummaryFilenameRoute =
  DashboardSummaryFilenameRouteImport.update({
    id: '/summary/$filename',
    path: '/summary/$filename',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardQuizFilenameRoute = DashboardQuizFilenameRouteImport.update({
  id: '/quiz/$filename',
  path: '/quiz/$filename',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMcqFilenameRoute = DashboardMcqFilenameRouteImport.update({
  id: '/mcq/$filename',
  path: '/mcq/$filename',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardChatFilenameRoute = DashboardChatFilenameRouteImport.update({
  id: '/chat/$filename',
  path: '/chat/$filename',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/upload': typeof UploadRoute
  '/admin/subject-library': typeof AdminSubjectLibraryRoute
  '/dashboard/repository': typeof DashboardRepositoryRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/subject-library': typeof DashboardSubjectLibraryRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/chat/$filename': typeof DashboardChatFilenameRoute
  '/dashboard/mcq/$filename': typeof DashboardMcqFilenameRoute
  '/dashboard/quiz/$filename': typeof DashboardQuizFilenameRoute
  '/dashboard/summary/$filename': typeof DashboardSummaryFilenameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/upload': typeof UploadRoute
  '/admin/subject-library': typeof AdminSubjectLibraryRoute
  '/dashboard/repository': typeof DashboardRepositoryRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/subject-library': typeof DashboardSubjectLibraryRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/chat/$filename': typeof DashboardChatFilenameRoute
  '/dashboard/mcq/$filename': typeof DashboardMcqFilenameRoute
  '/dashboard/quiz/$filename': typeof DashboardQuizFilenameRoute
  '/dashboard/summary/$filename': typeof DashboardSummaryFilenameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/upload': typeof UploadRoute
  '/admin/subject-library': typeof AdminSubjectLibraryRoute
  '/dashboard/repository': typeof DashboardRepositoryRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/subject-library': typeof DashboardSubjectLibraryRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/chat/$filename': typeof DashboardChatFilenameRoute
  '/dashboard/mcq/$filename': typeof DashboardMcqFilenameRoute
  '/dashboard/quiz/$filename': typeof DashboardQuizFilenameRoute
  '/dashboard/summary/$filename': typeof DashboardSummaryFilenameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/dashboard'
    | '/help'
    | '/login'
    | '/signup'
    | '/upload'
    | '/admin/subject-library'
    | '/dashboard/repository'
    | '/dashboard/settings'
    | '/dashboard/subject-library'
    | '/admin/'
    | '/dashboard/'
    | '/dashboard/chat/$filename'
    | '/dashboard/mcq/$filename'
    | '/dashboard/quiz/$filename'
    | '/dashboard/summary/$filename'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/help'
    | '/login'
    | '/signup'
    | '/upload'
    | '/admin/subject-library'
    | '/dashboard/repository'
    | '/dashboard/settings'
    | '/dashboard/subject-library'
    | '/admin'
    | '/dashboard'
    | '/dashboard/chat/$filename'
    | '/dashboard/mcq/$filename'
    | '/dashboard/quiz/$filename'
    | '/dashboard/summary/$filename'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/dashboard'
    | '/help'
    | '/login'
    | '/signup'
    | '/upload'
    | '/admin/subject-library'
    | '/dashboard/repository'
    | '/dashboard/settings'
    | '/dashboard/subject-library'
    | '/admin/'
    | '/dashboard/'
    | '/dashboard/chat/$filename'
    | '/dashboard/mcq/$filename'
    | '/dashboard/quiz/$filename'
    | '/dashboard/summary/$filename'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  HelpRoute: typeof HelpRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  UploadRoute: typeof UploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/dashboard/subject-library': {
      id: '/dashboard/subject-library'
      path: '/subject-library'
      fullPath: '/dashboard/subject-library'
      preLoaderRoute: typeof DashboardSubjectLibraryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/repository': {
      id: '/dashboard/repository'
      path: '/repository'
      fullPath: '/dashboard/repository'
      preLoaderRoute: typeof DashboardRepositoryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/subject-library': {
      id: '/admin/subject-library'
      path: '/subject-library'
      fullPath: '/admin/subject-library'
      preLoaderRoute: typeof AdminSubjectLibraryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/dashboard/summary/$filename': {
      id: '/dashboard/summary/$filename'
      path: '/summary/$filename'
      fullPath: '/dashboard/summary/$filename'
      preLoaderRoute: typeof DashboardSummaryFilenameRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/quiz/$filename': {
      id: '/dashboard/quiz/$filename'
      path: '/quiz/$filename'
      fullPath: '/dashboard/quiz/$filename'
      preLoaderRoute: typeof DashboardQuizFilenameRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/mcq/$filename': {
      id: '/dashboard/mcq/$filename'
      path: '/mcq/$filename'
      fullPath: '/dashboard/mcq/$filename'
      preLoaderRoute: typeof DashboardMcqFilenameRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/chat/$filename': {
      id: '/dashboard/chat/$filename'
      path: '/chat/$filename'
      fullPath: '/dashboard/chat/$filename'
      preLoaderRoute: typeof DashboardChatFilenameRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface AdminRouteChildren {
  AdminSubjectLibraryRoute: typeof AdminSubjectLibraryRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminSubjectLibraryRoute: AdminSubjectLibraryRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DashboardRouteChildren {
  DashboardRepositoryRoute: typeof DashboardRepositoryRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardSubjectLibraryRoute: typeof DashboardSubjectLibraryRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardChatFilenameRoute: typeof DashboardChatFilenameRoute
  DashboardMcqFilenameRoute: typeof DashboardMcqFilenameRoute
  DashboardQuizFilenameRoute: typeof DashboardQuizFilenameRoute
  DashboardSummaryFilenameRoute: typeof DashboardSummaryFilenameRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardRepositoryRoute: DashboardRepositoryRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardSubjectLibraryRoute: DashboardSubjectLibraryRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardChatFilenameRoute: DashboardChatFilenameRoute,
  DashboardMcqFilenameRoute: DashboardMcqFilenameRoute,
  DashboardQuizFilenameRoute: DashboardQuizFilenameRoute,
  DashboardSummaryFilenameRoute: DashboardSummaryFilenameRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  HelpRoute: HelpRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  UploadRoute: UploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
